##spring:

  ##thymeleaf:
   ## cache: false

  ##datasource:
   ## url: jdbc:mysql://localhost:3306/hr?useUnicode=true&characterEncoding=utf-8&useSSL=trueusername: root
    ##password: 12345
   ## driver-class-name: com.mysql.jdbc.Driver


